# -*- coding: utf-8 -*-
"""A13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZIfqAWHK1twfX6-c_ZCwqBJm5NdnjP8a
"""

num=10
count=0
for i in range(1,11):
  if(num%i==0):
    print("factor is :",i)
    count+=1
print("no of factors are",count)

#Prime number
num=8
count=0
print("number is:",num)
for i in range(1,num+1):
  if(num%i==0):
    count+=1
    print("factors are:",i)
if(count>2):
  print("Hence not prime")
else:
  print("hence Prime")

for i in range(1,4):
  if(i==3):
    break
  print("loop",i)
print("Akshat")

num=9
for i  in range(2,num):
  if(num%i==0):
    print("Not a prime", num)
    break
else:
  print("prime",num)

num=7
a=0       #indicator variable
for i in range(2,num):
  if(num%i==0):
    a=1
    break
if(a==1):
  print("not prime",num)
else:
  print("Prime")

# WHILE LOOP (Number of iterations are not specified)

i=3
while(i<6):
  print("hey ",i)
  i+=1

i=1
total=0
while(i<101):
  total=total+i
  i+=1
print(total)

i=20
while(i<41):
  if(i%3==0):
    print(i)
  i+=1

i=98
count=0
while(i>=58):

  i-=1
  count+=1
print(count)

num=169
count=0
while(num>0):
  rem1=num%10
  num=num//10
  count+=1

  print(rem1,num)
print("count of digits",count)

num=123
sum=0
while(num>0):
  rem1=num%10
  num=num//10
  sum=sum+rem1
print(sum)

#ARMSTRONG
num=153
num1=num
total=0

while(num>0):
  rem=num%10
  num=num//10
  print(rem,rem**3)
  total=total+(rem**3)
print(total)

print()

if(total==num1):
  print("ARMSTRONG")
else:
  print("NOT ARMSTRONG")

x=256
y=256

print(id(x), id(y))

#data value from zero to 256 adress are same

x=10
y=x
print(id(x), id(y))

#PALINDROME NUMBER OR STRING
s="NAMAN"
i=0
end=len(s)-1
a=0
while(i<end):

  if(s[i]!= s[end]):
    a=1
    break
  i+=1
  end-=1

if(a==1):
  print("Not a palandrome",s)
else:
  print("A palandrome",s)

#SLICING & INDEXING
city="JAIPUR"
city[-6]
city[0:4]

city="JAIPUR"
city[0:3]

city="JAIPUR"
city[2:6:2]

city="JAIPUR"
city[-1:-3:-1]

# NESTED FOR LOOP

for i in range(1,5):
  print("--Student",i)



  for j in range(1,5):
    print("--Subject",j)

  print()

for i in range(4,1,-1):
  print("--Student",i)



  for j in range(1,5):
    print("--Subject",j)
  print()

for i in range(1,5):
  print("--Student",i)



  for j in range(1,i+1): #to print sub equal to student number 1 for 1, 2 for 2
    print("Subject",j)
  print()

for i in range(1,5):
  print("--Student",i)



  for j in range(i,5):
    print("--Subject",j)
  print()

for i in range(1,5):
  print("--Student",i)



  for j in range(1,5-i +1):
    print("--Subject",j)
  print()

for i in range(1,5):
  print("--Student",i)



  for j in range(1,5):
    print("--Subject",j)
  print()

  print("Tea Break")
  print()

for i in range(1,5):
  print("--Student",i)



  for j in range(1,5-i+1):
    print("--Subject",j,end=" ")
  print()

for i in range(1,5):
  for j in range(1,5):
    print("*",end=" ")
  print("")

for i in range(1,5):
  for j in range(1,5):
    print(i,end=" ")
  i+=1
  print()

for i in range(1,5):
  for j in range(1,5):
    print(j,end=" ")
    j+=1
  print()

for i in range(1,5):
  for j in range(4,0,-1):
    print(j,end=" ")
    j-=1
  print()

for i in range(4,1,-1):
  for j in range(1,5):
    print(i,end=" ")
  i-=1
print()

num=1
for i in range(1,4):
  for j in range(1,4):
    print(num,end=" ")
    num+=1
  print()

for i in range(1,5):
  for j in range(1,5):
    print(j,end=" ")
    j+=1
  print()

for i in range(1,5):
  for j in range(1,i+1):
    print("*",end=" ")
  print()

for i in range(1,4):
  for j in range(1,i+1):
    print(j,end=" ")
  print()

for i in range(1,4):
  for j in range(1,i+1):
    print(j+3,end=" ")
  print()

x=4
for i in range(1,4):

  for j in range(1,i+1):
    print(x,end=" ")
  x-=1
  print()

for i in range(4,0,-1):
  for j in range(i):
    print("*",end=" ")

  print()

x=10
for i in range(1,4):
  for j in range(1,i+1):
    print(x,end=" ")
    x+=1
  print()

x=10
for i in range(1,4):
  for j in range(i+1):
    print(x+j,end=" ")
  x+=1
  print()

for i in range(1,6):
  for j in range(i):
    print("-",end=" ")

for i in range(1,6):
  for k in range(1,5-i+1):
    print("*",end=" ")
  print()

for i in range(1,6):
  for j in range(i):
    print("-",end=" ")

  for k in range(1,5-i+1):
    print("*",end=" ")

  print()

for i in range(1,6):
  for j in range(1,5-i+1):
    print("-",end=" ")

  for k in range(i):
    print("*",end=" ")
  print()

for i in range(1,6):
  x=65
  for j in range(1,i+1):
    print(j,end=" ")

  for k in range(1,5-i+1):
    print(chr(x),end=" ")
    x+=1
  print()

for i in range(1,5):
  for j in range(0,i+1):
    print(" ",end=" ")

  for k in range(1,5-i+1):
    print("*",end=" ")

  print()

for i in range(1,6):
  for k in range(1,i+1):
    if(k==1 or i==5 or i==k):
      print("*",end=" ")
    else:
      print("-",end=" ")
  print()

for i in range(5,0,-1):
  for k in range(1,i+1):
    if(k==1 or i==5 or i==k):
      print("*",end=" ")
    else:
      print(" ",end=" ")
  print()

for i in range(1,6):
  for j in range(i-1):
    print("-",end=" ")

  for k in range(1,6):
    if(k==5 or i==1 or k==i):
      print("*", end=" ")
    else:
      print(" ",end=" ")
  print()

for i in range(1,6):
  for k in range(1,6):
    if(k==5 or i==1 or k==i):
      print("*", end=" ")
    else:
      print(" ",end=" ")
  print()