# -*- coding: utf-8 -*-
"""Forloop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kOeDMf-ZavuDqc32rCIawrDTYV9kaN5a
"""

#Natural numbers
n=int(input("Enter the Number"))
for i in range (1,n+1,1):
  print("the Natural numbers are ",i)

#Reverse Natural
n=int(input("Enter the Number"))
for i in range (n,0,-1):
  print("the Natural numbers are ",i)

#Alphabet Printing
for i in range(ord('a'),ord("z")+1):
  print(chr(i))

#Even number printing
for i in range(1,101,1):
  if(i%2==0):
    print(i)

#Odd sum
n=int(input("Enter the range"))
sum=0
for i in range(1,n+1):
  if(i%2!=0):
    sum=sum+i
print("The sum of all odd numbers from 1 to n is ",sum)

#Digits of number
num=int(input("Enter the number"))
count=0
for _ in str(num):
  count=count+1
print(count)

#First & Last digit
num=int(input("Enter the number"))
number_str=str(num)
print(number_str[0])
print(number_str[-1])

# Sum of First & Last digit
num=int(input("Enter the number"))
number_str=str(num)
x=int(number_str[0])
y=int(number_str[-1])
sum=x+y
print("The sum is ",sum)