# -*- coding: utf-8 -*-
"""Nestedloop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uecAJ87QTTX711oFij5SxmOcYP8UKmL5
"""

for i in range(1,6):
  print("---student",i)

  for j in range(1,4):
    print("subject",j)

for i in range(1,6):
  print("---student",i)

  for j in range(1,i+1):
    print("subject",j)

for i in range(1,6):
  print("---student",i)

  for j in range(1,6-i):
    print("subject",j)

for i in range(4,0,-1):
  print("---student",i)

  for j in range(1,6-i):
    print("subject",j)

#table
num=2
for i in range(1,11):
  print(num*i)

for num in range(2,6):
  for i in range(1,11):
    print(num*i)
  print("*****")
  print("Next table is ")
  print("*****")

for num in range(2,10):
  for i in range(1,num+1):
    if(num%i==0):
      print("factor",i)
  print("---")

num=8
for i in range(1,num+1):
  if(num%i==0):
    print("Factor =>",i)

for num in range(2,8):
  for i in range(1,num+1):
    if(num%i==0):
      print("Factor =>",i)
  print("------")

num=154
total=0
x=num
while(num>0):
  rem=num%10
  num=num//10
  total=total+rem**3
  print(rem**3,num)
  print(total)
if(total==x):
  print("ARMSTRONG")
else:
  print("Not a Armstrong")

#narcissistic number
#153= 1**3 +5**3 +3**3
#1234=1**4 + 2**4 + 3**4 + 4**4


for num in range (150,401):
  total=0
  x=num
  while(num>0):
    rem=num%10
    num=num//10
    total=total+rem**3

  if(total==x):
    print("ARMSTRONG",x)

