# -*- coding: utf-8 -*-
"""Patterns.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C0K2BhmBrgNoaTmolf-arSH3fQjDn-0_
"""

# Star(*) pattern
for i in range(1,5):
  for j in range(1,5):
    print("*",end=" ")
  print("")

# Star(*) pattern
for i in range(1,6):
  for j in range(1,5):
    print("*",end=" ")
  print("")

for i in range(1,5):
  for j in range(1,4):
    print("*",end="")
  print("")

for i in range(1,5):
  for j in range(1,5):
    print("1",end="")
  print("")

for i in range(1,4):
  for j in range(1,2):
    print("1234",end=" ")
  print("")

for i in range(4,0,-1):
  for j in range(1,5):
    print(i,end="")
  print("")

for i in range(1,4):
  for j in range(1,2):
    print("5678",end="")
  print("")

x=1
for i in range(1,4):
  for j in range(1,4):
    print(x,end="")
    x+=1

  print("")

for i in range(1,4):
  for j in range(1,2):
    print("ABC",end="")
  print("")

for i in range(1,7):
  for j in range(1,i+1):
    print("*",end="")
  print("")

for i in range(1,5):
  for j in range(1,i+1):
    print(i,end="")
  print("")

x=5
for i in range(1,4):
  for j in range(1,i+1):
    print(x,end="")
    x+=1
  print("")

num=5
for i in range(0,3):
    for j in range(i + 1):
        print(num + i, end="")
    print()

for i in range(5,0,-1):
  for j in range(1,i+1):
    print("*",end="")
  print("")

num = 9
for i in range(4):
    for j in range(4 - i):
        print(num, end="")
        num -= 1
    print()