# -*- coding: utf-8 -*-
"""Tuple&Dictionary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dm1hIWDOpImcUF8Rv-v__Y4saqeZyKf1
"""

#TUPLE => immutable, data types are collected on the basis of index
x=10,20
print(type(x))

x=(10,20)
print(type(x))

x-(10,20)
x[0]=19     #this is mot allowed

#1 Count => count the number of values occuring
#2 Index => position of the value

x=(10,20,10,40,4,10,)
print(x.count(10))
print(x.count(4))

# Dictionary : datatype => stores data but without index
#data is stored in key and value format
#key => unique data
'''
101 (key) [unique] => product ,how much ,etc(value) [can be duplicate]


they are ordered datatypes

they dont have any index values

this reduces the time complexity
'''

dict={101:"Akki", "salary":10000, "email":"XYZ"}
print(dict)

dict={101:"Akki", "salary":10000, "email":"XYZ"}
print(dict["salary"])

dict={101:"Akki", "salary":10000, "email":"XYZ"}
x=dict.pop(101)
print(dict,x)

dict={10:"a",20:"b"}
for i in dict:
  print(i,dict[i])

dict={101:"Akki", "salary":10000, "email":"XYZ"}
print(dict.keys())

dict={10:"a",20:"b"}
for i in dict.values():
  print(i)

dict={101:"Akki", "salary":10000, "email":"XYZ"}
print(dict.values())

# TO add a values to exisiting figure(ADD)
dict={10:'a',"amount":1000}
dict["amount"]=dict["amount"]+5
print(dict)

dict={101:"Akki", "salary":10000, "email":"XYZ"}
dict[101]="Akshat"
print(dict)

#To count the number of characters in a string without len function
s = "Raj"
d = {'total':0}
for i in s:
    d["total"]+=1
print(d)

# TO form key value pair

s = "abc"
x = {}
for i in s:
    if i in x:
        x[i]+=1
    else:
        x[i]=1
print(x)

dict={}
for i in 'abc':
  dict[i]=1   #TO add values as a key in a dictionary

print(dict)

